-- MySQL Script generated by MySQL Workbench
-- Sun Sep  6 12:06:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_megalaudo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_megalaudo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_megalaudo` DEFAULT CHARACTER SET utf8 ;
USE `db_megalaudo` ;

-- -----------------------------------------------------
-- Table `db_megalaudo`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_megalaudo`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `anoModelo` YEAR NOT NULL,
  `anoFabricacao` YEAR NOT NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megalaudo`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_megalaudo`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(15) NOT NULL,
  `Endereco` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_megalaudo`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_megalaudo`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(450) NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Valor` DOUBLE(10,2) NOT NULL,
  PRIMARY KEY (`idServico`),
  INDEX `fk_Servico_Veiculo_idx` (`Veiculo_idVeiculo` ASC),
  INDEX `fk_Servico_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Servico_Veiculo`
    FOREIGN KEY (`Veiculo_idVeiculo`)
    REFERENCES `db_megalaudo`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `db_megalaudo`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
